/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnihybridstack_JNIStackImplementation */

#ifndef _Included_jnihybridstack_JNIStackImplementation
#define _Included_jnihybridstack_JNIStackImplementation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    push
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jnihybridstack_JNIStackImplementation_push
  (JNIEnv *, jobject, jint);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    peek
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnihybridstack_JNIStackImplementation_peek
  (JNIEnv *, jobject);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jnihybridstack_JNIStackImplementation_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnihybridstack_JNIStackImplementation_show
  (JNIEnv *, jobject);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    remove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnihybridstack_JNIStackImplementation_remove
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
