/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnihybridstack_JNIStackImplementation */

#ifndef _Included_jnihybridstack_Stack
#define _Included_jnihybridstack_Stack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    init
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jnihybridstack_Stack_init
  (JNIEnv *, jobject);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    push
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_jnihybridstack_Stack_push
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    peek
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jnihybridstack_Stack_peek
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    isEmpty
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_jnihybridstack_Stack_isEmpty
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    pop
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jnihybridstack_Stack_pop
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jnihybridstack_JNIStackImplementation
 * Method:    cloneBuffer
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jnihybridstack_Stack_cloneBuffer
  (JNIEnv *, jobject, jbyteArray);

void replace_cpp_exception_by_java_exception(JNIEnv *);

#ifdef __cplusplus
}
#endif
#endif
